FROM python:3.11-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir mlflow

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:///mlflow-data/mlflow.db", \
     "--default-artifact-root", "/mlflow-data/artifacts", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--allowed-hosts", "*"]