version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telco-churn-api
    ports:
      - "8080:8000"
    depends_on:
      - mlflow
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: telco-churn-mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow-data
    restart: unless-stopped

volumes:
  mlflow-data: